name: Release

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '!v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
    workflow_dispatch:

jobs:
    CreateRelease:
        name: CreateRelease
        uses: EncoreDigitalGroup/.github/.github/workflows/createRelease.yml@v1
        with:
            generate_release_notes: true
            is_draft: false
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}

    SplitMonorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    - Common
                    - Logger
        steps:
            -   uses: actions/checkout@v3
            -   id: previousTag
                uses: 'WyriHaximus/github-action-get-previous-tag@master'

            -   name: Monorepo Split of ${{ matrix.package }}
                uses: danharrin/monorepo-split-github-action@v2.3.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_MONOREPO_SPLIT_TOKEN }}
                with:
                    package_directory: 'src/${{ matrix.package }}'
                    repository_organization: 'PHPGenesis'
                    repository_name: '${{ matrix.package }}'
                    branch: main
                    tag: ${{ steps.previousTag.outputs.tag }}
                    user_name: 'GenesisBot'
                    user_email: 'ghbot@phpgenesis.com'

    SplitMonorepoServices:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    - AmazonWebServices
        steps:
            -   uses: actions/checkout@v3
            -   id: previousTag
                uses: 'WyriHaximus/github-action-get-previous-tag@master'

            -   name: Monorepo Split of ${{ matrix.package }}
                uses: danharrin/monorepo-split-github-action@v2.3.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_MONOREPO_SPLIT_TOKEN }}
                with:
                    package_directory: 'src/Services/${{ matrix.package }}'
                    repository_organization: 'PHPGenesis'
                    repository_name: '${{ matrix.package }}'
                    branch: main
                    tag: ${{ steps.previousTag.outputs.tag }}
                    user_name: 'GenesisBot'
                    user_email: 'ghbot@phpgenesis.com'